### ISSUE TITLE
MS SharePoint REST API and root path

### ISSUE THREAD

**Issue by mikekaganski** [tdf/libcmis#10]
To use MS SharePoint 2013 REST API in LibreOffice, I choose SharePoint 2013 type and get this host template string:
`http://<host>/_api/Web`
I need to substitute `<host>` with my sharepoint site path, like this: sharepoint2013/sites/mysite, so the overall result looks like this:
http://sharepoint2013/sites/mysite/_api/Web
Then I choose the repository, that is SharePoint. That repository is defined in libcmis's src/libcmis/sharepoint-repository.[hc]xx
In it, the m_rootId is defined as `baseUrl + "/getFolderByServerRelativeUrl('/')"`
But that's incorrect, because this will try to get the object http://sharepoint2013/, while the real root for this site is http://sharepoint2013/sites/mysite/. (You know, that getFolderByServerRelativeUrl API is used, that is server-relative as the name suggests, not site-relative; see e.g. http://stackoverflow.com/questions/21254703/web-getfilebyserverrelativeurl-throws-value-does-not-fall-within-expected-range). Sharepoint does throw the "Value does not fall within expected range" error for that URL.
So, ideally, there should be `baseUrl + "/getFolderByServerRelativeUrl('/sites/mysite/')"`, but that's unclear how to do that reliably, because that requires parsing the baseURL and stripping both server (which is easy) **and** API part like "_api/Web", and I don't know if that's good to search for that string hard-coded.
However, I found out that using just `baseUrl + "/getFolderByServerRelativeUrl('')"` works OK instead. I don't know if that is OK to do that, and wouldn't that be context-dependent. Could you please advise me how to best deal with this to make a patch.

**Comment by dtardon** [comment]
If it works, let's use it...
