### ISSUE TITLE
New release with dynamic exception specifications dropped

### ISSUE THREAD

**Issue by stbergmann** [tdf/libcmis#24]
LibreOffice master requires a C++17 compiler now, so configuring it --with-system-libcmis fails when including libcmis headers that still use dynamic exception specifications.  (The LibreOffice --without-system-libcmis case is covered through a local external/libcmis/c++17.patch.0.)
Therefore, it would be helpful if there were an official libcmis release that includes <https://github.com/tdf/libcmis/commit/172e83762b2b4b300073212ffd841dc90680bb86> "Merge pull request #16 from vmiklos/dynexcspec: Remove dynamic exception specifications".

**Comment by dtardon** [comment]
Yes, a new release is on my TODO list.
