### ISSUE TITLE
Any plans to make new release?

### ISSUE THREAD

**Issue by kloczek** [tdf/libcmis#42]
I think that it would be good to flush currently committed changes and make new release :)

**Comment by jospezial** [comment]
Would be great with the libreoffice patches and when #44 is merged.

**Comment by heirecka** [comment]
Ping? :)

Anything one could help with?

**Comment by jospezial** [comment]
@caolanm 
https://github.com/tdf/libcmis/releases/tag/v0.6.0 is not listed in https://github.com/tdf/libcmis/releases tab

**Comment by caolanm** [comment]
Seems to be there, unless I'm missing something obvious?

![image](https://github.com/tdf/libcmis/assets/833656/58eea85e-c816-45ff-acd1-9f1e29f1d531)

**Comment by jospezial** [comment]
For me 0.5.2 and 0.5.1 are listed in releases.
In tags are all listed.
Tested with firefox and lynx on 2 different computers (Gentoo, OpenSuse TW). No proxy.
I even powercycled my vdsl-router.
Are the github servers not synced?
@caolanm How does github.com resolve for you?
@kloczek and @heirecka what do you see at releases tab?

```
PING github.com (140.82.121.4) 56(84) Bytes an Daten.
64 Bytes von lb-140-82-121-4-fra.github.com (140.82.121.4): icmp_seq=1 ttl=54 Zeit=14.8 ms
```

**Comment by kloczek** [comment]
![image](https://github.com/tdf/libcmis/assets/31284574/e8709668-bebd-45f8-a560-a6a77908b756)

**Comment by jospezial** [comment]
The question was what you see on releases tab as caolanm posted.

**Comment by kloczek** [comment]
Only to gh releases
![image](https://github.com/tdf/libcmis/assets/31284574/352e7ebe-1fa8-47cf-be69-6bf626425579)

**Comment by caolanm** [comment]
hmm, when I was logged out it didn't appear. I've clicked "update release" now and it seems to exist for everyone now?

**Comment by kloczek** [comment]
Just checked one more time.
Now I see new 0.6.0 as well.

**Comment by caolanm** [comment]
well, we have a release, and now it appears visible

**Comment by jospezial** [comment]
Thank you.
