### ISSUE TITLE
Question: how to build on MS Windows ?

### ISSUE THREAD

**Issue by nicerloop** [tdf/libcmis#72]
Hi,

I understand this library is used in LibreOffice, which provides Windows binaries.
So Windows binaries can be build from these sources.
How can I also build this library  and accompanying command-line tool for Windows?
Do I need to cross-compile from Linux?

Thank you.

**Comment by mistmist** [comment]
LibreOffice simply uses a makefile in its own build system to build libcmis, it does not invoke the libcmis build system on any platform.
So perhaps you could try something similar.

**Comment by nicerloop** [comment]
Thank you, I will have a look at LibreOffice makefiles.
